zonename="ZONE_NAME"
zonepath="/zones/ZONE_NAME"

autoboot="false"
brand="bhyve"

# CHANGME
cdrom="/rpool/zone-data/debian-12.7.0-amd64-netinst.iso"

ram="1G"
vcpus="2"
xhci="on"
vnc="on"
bootorder="cd"
ip-type="exclusive"
limitpriv="default"

[capped-memory]
physical="1G"
swap="1G"

[bootdisk]
blocksize="8k"
path="rpool/zones/ZONE_NAME/root"
size="8G"
sparse="true"

[[net]]
allowed-address="IP"
defrouter="10.10.10.1"
global-nic="switch0"
physical="ZONE_NAME"

[[fs]]
dir="/data"
special="/zones/ZONE_NAME/data"
type="lofs"
options=[]

[[virtfs]]
name="data"
path="/data"
ro="false"
