zonename="ZONE_NAME"
zonepath="/zones/ZONE_NAME"

autoboot="false"
brand="illumos"

ip-type="exclusive"
resolvers=[
    "1.1.1.1",
]
[dedicated-cpu]
ncpus="4.00"

[capped-cpu]
ncpus="4.00"

[capped-memory]
physical="4G"
swap="8G"

[[fs]]
dir="/server"
special="/zones/data/ZONE_NAME"
type="lofs"
options=[]

[[dataset]]
name="rpool/zones/ZONE_NAME/data"

[[net]]
allowed-address="IP"
defrouter="10.10.10.1"
global-nic="switch0"
physical="ZONE_NAME"
