zonename="ZONE_NAME"
zonepath="/zones/ZONE_NAME"

autoboot="false"
brand="lipkg"

ip-type="exclusive"
resolvers=[
    "1.1.1.1",
]

[capped-cpu]
ncpus="2.00"

[capped-memory]
physical="2G"
swap="4G"

[[fs]]
dir="/data"
special="/zones/ZONE_NAME/data"
type="lofs"
options=[]

[[net]]
allowed-address="IP"
defrouter="10.10.10.1"
global-nic="switch0"
physical="ZONE_NAME"
